/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NumberWorldRouteImport } from './routes/number-world'
import { Route as IndexRouteImport } from './routes/index'

const NumberWorldRoute = NumberWorldRouteImport.update({
  id: '/number-world',
  path: '/number-world',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/number-world': typeof NumberWorldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/number-world': typeof NumberWorldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/number-world': typeof NumberWorldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/number-world'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/number-world'
  id: '__root__' | '/' | '/number-world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NumberWorldRoute: typeof NumberWorldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/number-world': {
      id: '/number-world'
      path: '/number-world'
      fullPath: '/number-world'
      preLoaderRoute: typeof NumberWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NumberWorldRoute: NumberWorldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
