/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TraceWordsRouteImport } from './routes/trace-words'
import { Route as TraceVarnamalaRouteImport } from './routes/trace-varnamala'
import { Route as TraceSmallRouteImport } from './routes/trace-small'
import { Route as TraceShabadRouteImport } from './routes/trace-shabad'
import { Route as TraceNumbersRouteImport } from './routes/trace-numbers'
import { Route as TraceCapitalRouteImport } from './routes/trace-capital'
import { Route as TestKnowledgeRouteImport } from './routes/test-knowledge'
import { Route as SmartLearningRouteImport } from './routes/smart-learning'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScribbleTraceRouteImport } from './routes/scribble-trace'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NumberWorldRouteImport } from './routes/number-world'
import { Route as MathsChallengeRouteImport } from './routes/maths-challenge'
import { Route as LearnClockRouteImport } from './routes/learn-clock'
import { Route as FunPhoneRouteImport } from './routes/fun-phone'
import { Route as ColorsNameRouteImport } from './routes/colors-name'
import { Route as ColorsListRouteImport } from './routes/colors-list'
import { Route as BrainQuizRouteImport } from './routes/brain-quiz'
import { Route as AnimalKingdomRouteImport } from './routes/animal-kingdom'
import { Route as AbcWorldRouteImport } from './routes/abc-world'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceWordsRoute = TraceWordsRouteImport.update({
  id: '/trace-words',
  path: '/trace-words',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceVarnamalaRoute = TraceVarnamalaRouteImport.update({
  id: '/trace-varnamala',
  path: '/trace-varnamala',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceSmallRoute = TraceSmallRouteImport.update({
  id: '/trace-small',
  path: '/trace-small',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceShabadRoute = TraceShabadRouteImport.update({
  id: '/trace-shabad',
  path: '/trace-shabad',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceNumbersRoute = TraceNumbersRouteImport.update({
  id: '/trace-numbers',
  path: '/trace-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceCapitalRoute = TraceCapitalRouteImport.update({
  id: '/trace-capital',
  path: '/trace-capital',
  getParentRoute: () => rootRouteImport,
} as any)
const TestKnowledgeRoute = TestKnowledgeRouteImport.update({
  id: '/test-knowledge',
  path: '/test-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartLearningRoute = SmartLearningRouteImport.update({
  id: '/smart-learning',
  path: '/smart-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScribbleTraceRoute = ScribbleTraceRouteImport.update({
  id: '/scribble-trace',
  path: '/scribble-trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NumberWorldRoute = NumberWorldRouteImport.update({
  id: '/number-world',
  path: '/number-world',
  getParentRoute: () => rootRouteImport,
} as any)
const MathsChallengeRoute = MathsChallengeRouteImport.update({
  id: '/maths-challenge',
  path: '/maths-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnClockRoute = LearnClockRouteImport.update({
  id: '/learn-clock',
  path: '/learn-clock',
  getParentRoute: () => rootRouteImport,
} as any)
const FunPhoneRoute = FunPhoneRouteImport.update({
  id: '/fun-phone',
  path: '/fun-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsNameRoute = ColorsNameRouteImport.update({
  id: '/colors-name',
  path: '/colors-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsListRoute = ColorsListRouteImport.update({
  id: '/colors-list',
  path: '/colors-list',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainQuizRoute = BrainQuizRouteImport.update({
  id: '/brain-quiz',
  path: '/brain-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalKingdomRoute = AnimalKingdomRouteImport.update({
  id: '/animal-kingdom',
  path: '/animal-kingdom',
  getParentRoute: () => rootRouteImport,
} as any)
const AbcWorldRoute = AbcWorldRouteImport.update({
  id: '/abc-world',
  path: '/abc-world',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abc-world': typeof AbcWorldRoute
  '/animal-kingdom': typeof AnimalKingdomRoute
  '/brain-quiz': typeof BrainQuizRoute
  '/colors-list': typeof ColorsListRoute
  '/colors-name': typeof ColorsNameRoute
  '/fun-phone': typeof FunPhoneRoute
  '/learn-clock': typeof LearnClockRoute
  '/maths-challenge': typeof MathsChallengeRoute
  '/number-world': typeof NumberWorldRoute
  '/profile': typeof ProfileRoute
  '/scribble-trace': typeof ScribbleTraceRoute
  '/settings': typeof SettingsRoute
  '/smart-learning': typeof SmartLearningRoute
  '/test-knowledge': typeof TestKnowledgeRoute
  '/trace-capital': typeof TraceCapitalRoute
  '/trace-numbers': typeof TraceNumbersRoute
  '/trace-shabad': typeof TraceShabadRoute
  '/trace-small': typeof TraceSmallRoute
  '/trace-varnamala': typeof TraceVarnamalaRoute
  '/trace-words': typeof TraceWordsRoute
  '/welcome': typeof WelcomeRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abc-world': typeof AbcWorldRoute
  '/animal-kingdom': typeof AnimalKingdomRoute
  '/brain-quiz': typeof BrainQuizRoute
  '/colors-list': typeof ColorsListRoute
  '/colors-name': typeof ColorsNameRoute
  '/fun-phone': typeof FunPhoneRoute
  '/learn-clock': typeof LearnClockRoute
  '/maths-challenge': typeof MathsChallengeRoute
  '/number-world': typeof NumberWorldRoute
  '/profile': typeof ProfileRoute
  '/scribble-trace': typeof ScribbleTraceRoute
  '/settings': typeof SettingsRoute
  '/smart-learning': typeof SmartLearningRoute
  '/test-knowledge': typeof TestKnowledgeRoute
  '/trace-capital': typeof TraceCapitalRoute
  '/trace-numbers': typeof TraceNumbersRoute
  '/trace-shabad': typeof TraceShabadRoute
  '/trace-small': typeof TraceSmallRoute
  '/trace-varnamala': typeof TraceVarnamalaRoute
  '/trace-words': typeof TraceWordsRoute
  '/welcome': typeof WelcomeRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abc-world': typeof AbcWorldRoute
  '/animal-kingdom': typeof AnimalKingdomRoute
  '/brain-quiz': typeof BrainQuizRoute
  '/colors-list': typeof ColorsListRoute
  '/colors-name': typeof ColorsNameRoute
  '/fun-phone': typeof FunPhoneRoute
  '/learn-clock': typeof LearnClockRoute
  '/maths-challenge': typeof MathsChallengeRoute
  '/number-world': typeof NumberWorldRoute
  '/profile': typeof ProfileRoute
  '/scribble-trace': typeof ScribbleTraceRoute
  '/settings': typeof SettingsRoute
  '/smart-learning': typeof SmartLearningRoute
  '/test-knowledge': typeof TestKnowledgeRoute
  '/trace-capital': typeof TraceCapitalRoute
  '/trace-numbers': typeof TraceNumbersRoute
  '/trace-shabad': typeof TraceShabadRoute
  '/trace-small': typeof TraceSmallRoute
  '/trace-varnamala': typeof TraceVarnamalaRoute
  '/trace-words': typeof TraceWordsRoute
  '/welcome': typeof WelcomeRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abc-world'
    | '/animal-kingdom'
    | '/brain-quiz'
    | '/colors-list'
    | '/colors-name'
    | '/fun-phone'
    | '/learn-clock'
    | '/maths-challenge'
    | '/number-world'
    | '/profile'
    | '/scribble-trace'
    | '/settings'
    | '/smart-learning'
    | '/test-knowledge'
    | '/trace-capital'
    | '/trace-numbers'
    | '/trace-shabad'
    | '/trace-small'
    | '/trace-varnamala'
    | '/trace-words'
    | '/welcome'
    | '/games/$gameId'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abc-world'
    | '/animal-kingdom'
    | '/brain-quiz'
    | '/colors-list'
    | '/colors-name'
    | '/fun-phone'
    | '/learn-clock'
    | '/maths-challenge'
    | '/number-world'
    | '/profile'
    | '/scribble-trace'
    | '/settings'
    | '/smart-learning'
    | '/test-knowledge'
    | '/trace-capital'
    | '/trace-numbers'
    | '/trace-shabad'
    | '/trace-small'
    | '/trace-varnamala'
    | '/trace-words'
    | '/welcome'
    | '/games/$gameId'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/abc-world'
    | '/animal-kingdom'
    | '/brain-quiz'
    | '/colors-list'
    | '/colors-name'
    | '/fun-phone'
    | '/learn-clock'
    | '/maths-challenge'
    | '/number-world'
    | '/profile'
    | '/scribble-trace'
    | '/settings'
    | '/smart-learning'
    | '/test-knowledge'
    | '/trace-capital'
    | '/trace-numbers'
    | '/trace-shabad'
    | '/trace-small'
    | '/trace-varnamala'
    | '/trace-words'
    | '/welcome'
    | '/games/$gameId'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbcWorldRoute: typeof AbcWorldRoute
  AnimalKingdomRoute: typeof AnimalKingdomRoute
  BrainQuizRoute: typeof BrainQuizRoute
  ColorsListRoute: typeof ColorsListRoute
  ColorsNameRoute: typeof ColorsNameRoute
  FunPhoneRoute: typeof FunPhoneRoute
  LearnClockRoute: typeof LearnClockRoute
  MathsChallengeRoute: typeof MathsChallengeRoute
  NumberWorldRoute: typeof NumberWorldRoute
  ProfileRoute: typeof ProfileRoute
  ScribbleTraceRoute: typeof ScribbleTraceRoute
  SettingsRoute: typeof SettingsRoute
  SmartLearningRoute: typeof SmartLearningRoute
  TestKnowledgeRoute: typeof TestKnowledgeRoute
  TraceCapitalRoute: typeof TraceCapitalRoute
  TraceNumbersRoute: typeof TraceNumbersRoute
  TraceShabadRoute: typeof TraceShabadRoute
  TraceSmallRoute: typeof TraceSmallRoute
  TraceVarnamalaRoute: typeof TraceVarnamalaRoute
  TraceWordsRoute: typeof TraceWordsRoute
  WelcomeRoute: typeof WelcomeRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace-words': {
      id: '/trace-words'
      path: '/trace-words'
      fullPath: '/trace-words'
      preLoaderRoute: typeof TraceWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace-varnamala': {
      id: '/trace-varnamala'
      path: '/trace-varnamala'
      fullPath: '/trace-varnamala'
      preLoaderRoute: typeof TraceVarnamalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace-small': {
      id: '/trace-small'
      path: '/trace-small'
      fullPath: '/trace-small'
      preLoaderRoute: typeof TraceSmallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace-shabad': {
      id: '/trace-shabad'
      path: '/trace-shabad'
      fullPath: '/trace-shabad'
      preLoaderRoute: typeof TraceShabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace-numbers': {
      id: '/trace-numbers'
      path: '/trace-numbers'
      fullPath: '/trace-numbers'
      preLoaderRoute: typeof TraceNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace-capital': {
      id: '/trace-capital'
      path: '/trace-capital'
      fullPath: '/trace-capital'
      preLoaderRoute: typeof TraceCapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-knowledge': {
      id: '/test-knowledge'
      path: '/test-knowledge'
      fullPath: '/test-knowledge'
      preLoaderRoute: typeof TestKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-learning': {
      id: '/smart-learning'
      path: '/smart-learning'
      fullPath: '/smart-learning'
      preLoaderRoute: typeof SmartLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scribble-trace': {
      id: '/scribble-trace'
      path: '/scribble-trace'
      fullPath: '/scribble-trace'
      preLoaderRoute: typeof ScribbleTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/number-world': {
      id: '/number-world'
      path: '/number-world'
      fullPath: '/number-world'
      preLoaderRoute: typeof NumberWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maths-challenge': {
      id: '/maths-challenge'
      path: '/maths-challenge'
      fullPath: '/maths-challenge'
      preLoaderRoute: typeof MathsChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-clock': {
      id: '/learn-clock'
      path: '/learn-clock'
      fullPath: '/learn-clock'
      preLoaderRoute: typeof LearnClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fun-phone': {
      id: '/fun-phone'
      path: '/fun-phone'
      fullPath: '/fun-phone'
      preLoaderRoute: typeof FunPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors-name': {
      id: '/colors-name'
      path: '/colors-name'
      fullPath: '/colors-name'
      preLoaderRoute: typeof ColorsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors-list': {
      id: '/colors-list'
      path: '/colors-list'
      fullPath: '/colors-list'
      preLoaderRoute: typeof ColorsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain-quiz': {
      id: '/brain-quiz'
      path: '/brain-quiz'
      fullPath: '/brain-quiz'
      preLoaderRoute: typeof BrainQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animal-kingdom': {
      id: '/animal-kingdom'
      path: '/animal-kingdom'
      fullPath: '/animal-kingdom'
      preLoaderRoute: typeof AnimalKingdomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abc-world': {
      id: '/abc-world'
      path: '/abc-world'
      fullPath: '/abc-world'
      preLoaderRoute: typeof AbcWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbcWorldRoute: AbcWorldRoute,
  AnimalKingdomRoute: AnimalKingdomRoute,
  BrainQuizRoute: BrainQuizRoute,
  ColorsListRoute: ColorsListRoute,
  ColorsNameRoute: ColorsNameRoute,
  FunPhoneRoute: FunPhoneRoute,
  LearnClockRoute: LearnClockRoute,
  MathsChallengeRoute: MathsChallengeRoute,
  NumberWorldRoute: NumberWorldRoute,
  ProfileRoute: ProfileRoute,
  ScribbleTraceRoute: ScribbleTraceRoute,
  SettingsRoute: SettingsRoute,
  SmartLearningRoute: SmartLearningRoute,
  TestKnowledgeRoute: TestKnowledgeRoute,
  TraceCapitalRoute: TraceCapitalRoute,
  TraceNumbersRoute: TraceNumbersRoute,
  TraceShabadRoute: TraceShabadRoute,
  TraceSmallRoute: TraceSmallRoute,
  TraceVarnamalaRoute: TraceVarnamalaRoute,
  TraceWordsRoute: TraceWordsRoute,
  WelcomeRoute: WelcomeRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
